name: Latest blog post workflow
on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog post feed and update README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://mesirendon.com/index.xml"
          max_post_count: 5
