name: Generate GitHub stats images
on:
  schedule:
    # Runs every day at 3am UTC
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  generate-stats:
    name: Generate GitHub stats SVGs
    runs-on: ubuntu-latest
    steps:
      - name: Generate stats
        uses: jstrieb/github-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
